# encoding utf-8
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# database 세팅
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bank?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: hat1da2chi3go4bank5
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis 세팅
  data:
    redis:
      port: 6379
      host: redis
      password: ${SPRING_REDIS_PASSWORD}

# mybatis 세팅
mybatis:
  type-aliases-package: site.bank.restapi.*.mapper
  mapper-locations: static/mapper/*.xml

# log 설정
logging:
  level:
    root: info
    site.bank.restapi: debug

institution:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  client_role: ${CLIENT_ROLE}

jwt:
  key: ${SECRET_KEY}

