# database 세팅
# kakao login 설정 세팅
spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://marrymo.site:3306/marrymo?useSSL=false&serverTimezone=UTC
    username: root
    password: hat1da2chi3go4
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # aws application-aws.yml 사용
  profiles:
    active: aws

  h2:
     console:
       enabled: true
  # Mail Settings
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${USER_GMAIL}
    password: ${MAILAPP_PW}
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    auth-code-expiration-mills: 300000

  # spring data jpa 세팅
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # redis 세팅
  data:
    redis:
      port: 6379
      host: redis
      password: ${SPRING_REDIS_PASSWORD}

# log 설정
logging:
  level:
    root: info
    site.marrymo.restapi: debug

  # encoding utf-8
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


  #open-banking
open-banking:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}

mo-bank:
  client_id: ${MOBANK_CLIENT_ID}
  client_secret: ${MOBANK_CLEINT_SECRET}
  client_name: ${MOBANK_CLIENT_NAME}
  client_account: ${MOBANK_CLIENT_ACCOUNT}
